// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: leaderboard.proto
// </auto-generated>
// Original file comments:
// 指定 proto3 语法
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Leaderboard
{
    /// <summary>
    /// 定义排行榜服务
    /// </summary>
    public static partial class LeaderboardService
    {
        static readonly string __ServiceName = "leaderboard.LeaderboardService";

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
        {
#if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
            if (message is global::Google.Protobuf.IBufferMessage)
            {
                context.SetPayloadLength(message.CalculateSize());
                global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
                context.Complete();
                return;
            }
#endif
            context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
        }

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static class __Helper_MessageCache<T>
        {
            public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
        }

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
        {
#if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
            if (__Helper_MessageCache<T>.IsBufferMessage)
            {
                return parser.ParseFrom(context.PayloadAsReadOnlySequence());
            }
#endif
            return parser.ParseFrom(context.PayloadAsNewBuffer());
        }

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Leaderboard.SubmitScoreRequest> __Marshaller_leaderboard_SubmitScoreRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Leaderboard.SubmitScoreRequest.Parser));
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Leaderboard.SubmitScoreResponse> __Marshaller_leaderboard_SubmitScoreResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Leaderboard.SubmitScoreResponse.Parser));
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Leaderboard.GetTopPlayersRequest> __Marshaller_leaderboard_GetTopPlayersRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Leaderboard.GetTopPlayersRequest.Parser));
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Leaderboard.GetTopPlayersResponse> __Marshaller_leaderboard_GetTopPlayersResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Leaderboard.GetTopPlayersResponse.Parser));

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Method<global::Leaderboard.SubmitScoreRequest, global::Leaderboard.SubmitScoreResponse> __Method_SubmitScore = new grpc::Method<global::Leaderboard.SubmitScoreRequest, global::Leaderboard.SubmitScoreResponse>(
            grpc::MethodType.Unary,
            __ServiceName,
            "SubmitScore",
            __Marshaller_leaderboard_SubmitScoreRequest,
            __Marshaller_leaderboard_SubmitScoreResponse);

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Method<global::Leaderboard.GetTopPlayersRequest, global::Leaderboard.GetTopPlayersResponse> __Method_GetTopPlayers = new grpc::Method<global::Leaderboard.GetTopPlayersRequest, global::Leaderboard.GetTopPlayersResponse>(
            grpc::MethodType.Unary,
            __ServiceName,
            "GetTopPlayers",
            __Marshaller_leaderboard_GetTopPlayersRequest,
            __Marshaller_leaderboard_GetTopPlayersResponse);

        /// <summary>Service descriptor</summary>
        public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
        {
            get { return global::Leaderboard.LeaderboardReflection.Descriptor.Services[0]; }
        }

        /// <summary>Base class for server-side implementations of LeaderboardService</summary>
        [grpc::BindServiceMethod(typeof(LeaderboardService), "BindService")]
        public abstract partial class LeaderboardServiceBase
        {
            /// <summary>
            /// 客户端调用此接口提交分数
            /// </summary>
            /// <param name="request">The request received from the client.</param>
            /// <param name="context">The context of the server-side call handler being invoked.</param>
            /// <returns>The response to send back to the client (wrapped by a task).</returns>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::System.Threading.Tasks.Task<global::Leaderboard.SubmitScoreResponse> SubmitScore(global::Leaderboard.SubmitScoreRequest request, grpc::ServerCallContext context)
            {
                throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
            }

            /// <summary>
            /// 客户端调用此接口获取排行榜
            /// </summary>
            /// <param name="request">The request received from the client.</param>
            /// <param name="context">The context of the server-side call handler being invoked.</param>
            /// <returns>The response to send back to the client (wrapped by a task).</returns>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::System.Threading.Tasks.Task<global::Leaderboard.GetTopPlayersResponse> GetTopPlayers(global::Leaderboard.GetTopPlayersRequest request, grpc::ServerCallContext context)
            {
                throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
            }

        }

        /// <summary>Client for LeaderboardService</summary>
        public partial class LeaderboardServiceClient : grpc::ClientBase<LeaderboardServiceClient>
        {
            /// <summary>Creates a new client for LeaderboardService</summary>
            /// <param name="channel">The channel to use to make remote calls.</param>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public LeaderboardServiceClient(grpc::ChannelBase channel) : base(channel)
            {
            }
            /// <summary>Creates a new client for LeaderboardService that uses a custom <c>CallInvoker</c>.</summary>
            /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public LeaderboardServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
            {
            }
            /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            protected LeaderboardServiceClient() : base()
            {
            }
            /// <summary>Protected constructor to allow creation of configured clients.</summary>
            /// <param name="configuration">The client configuration.</param>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            protected LeaderboardServiceClient(ClientBaseConfiguration configuration) : base(configuration)
            {
            }

            /// <summary>
            /// 客户端调用此接口提交分数
            /// </summary>
            /// <param name="request">The request to send to the server.</param>
            /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
            /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
            /// <param name="cancellationToken">An optional token for canceling the call.</param>
            /// <returns>The response received from the server.</returns>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Leaderboard.SubmitScoreResponse SubmitScore(global::Leaderboard.SubmitScoreRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return SubmitScore(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            /// <summary>
            /// 客户端调用此接口提交分数
            /// </summary>
            /// <param name="request">The request to send to the server.</param>
            /// <param name="options">The options for the call.</param>
            /// <returns>The response received from the server.</returns>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Leaderboard.SubmitScoreResponse SubmitScore(global::Leaderboard.SubmitScoreRequest request, grpc::CallOptions options)
            {
                return CallInvoker.BlockingUnaryCall(__Method_SubmitScore, null, options, request);
            }
            /// <summary>
            /// 客户端调用此接口提交分数
            /// </summary>
            /// <param name="request">The request to send to the server.</param>
            /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
            /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
            /// <param name="cancellationToken">An optional token for canceling the call.</param>
            /// <returns>The call object.</returns>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Leaderboard.SubmitScoreResponse> SubmitScoreAsync(global::Leaderboard.SubmitScoreRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return SubmitScoreAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            /// <summary>
            /// 客户端调用此接口提交分数
            /// </summary>
            /// <param name="request">The request to send to the server.</param>
            /// <param name="options">The options for the call.</param>
            /// <returns>The call object.</returns>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Leaderboard.SubmitScoreResponse> SubmitScoreAsync(global::Leaderboard.SubmitScoreRequest request, grpc::CallOptions options)
            {
                return CallInvoker.AsyncUnaryCall(__Method_SubmitScore, null, options, request);
            }
            /// <summary>
            /// 客户端调用此接口获取排行榜
            /// </summary>
            /// <param name="request">The request to send to the server.</param>
            /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
            /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
            /// <param name="cancellationToken">An optional token for canceling the call.</param>
            /// <returns>The response received from the server.</returns>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Leaderboard.GetTopPlayersResponse GetTopPlayers(global::Leaderboard.GetTopPlayersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return GetTopPlayers(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            /// <summary>
            /// 客户端调用此接口获取排行榜
            /// </summary>
            /// <param name="request">The request to send to the server.</param>
            /// <param name="options">The options for the call.</param>
            /// <returns>The response received from the server.</returns>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Leaderboard.GetTopPlayersResponse GetTopPlayers(global::Leaderboard.GetTopPlayersRequest request, grpc::CallOptions options)
            {
                return CallInvoker.BlockingUnaryCall(__Method_GetTopPlayers, null, options, request);
            }
            /// <summary>
            /// 客户端调用此接口获取排行榜
            /// </summary>
            /// <param name="request">The request to send to the server.</param>
            /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
            /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
            /// <param name="cancellationToken">An optional token for canceling the call.</param>
            /// <returns>The call object.</returns>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Leaderboard.GetTopPlayersResponse> GetTopPlayersAsync(global::Leaderboard.GetTopPlayersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return GetTopPlayersAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            /// <summary>
            /// 客户端调用此接口获取排行榜
            /// </summary>
            /// <param name="request">The request to send to the server.</param>
            /// <param name="options">The options for the call.</param>
            /// <returns>The call object.</returns>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Leaderboard.GetTopPlayersResponse> GetTopPlayersAsync(global::Leaderboard.GetTopPlayersRequest request, grpc::CallOptions options)
            {
                return CallInvoker.AsyncUnaryCall(__Method_GetTopPlayers, null, options, request);
            }
            /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            protected override LeaderboardServiceClient NewInstance(ClientBaseConfiguration configuration)
            {
                return new LeaderboardServiceClient(configuration);
            }
        }

        /// <summary>Creates service definition that can be registered with a server</summary>
        /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        public static grpc::ServerServiceDefinition BindService(LeaderboardServiceBase serviceImpl)
        {
            return grpc::ServerServiceDefinition.CreateBuilder()
                .AddMethod(__Method_SubmitScore, serviceImpl.SubmitScore)
                .AddMethod(__Method_GetTopPlayers, serviceImpl.GetTopPlayers).Build();
        }

        /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
        /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
        /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
        /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        public static void BindService(grpc::ServiceBinderBase serviceBinder, LeaderboardServiceBase serviceImpl)
        {
            serviceBinder.AddMethod(__Method_SubmitScore, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Leaderboard.SubmitScoreRequest, global::Leaderboard.SubmitScoreResponse>(serviceImpl.SubmitScore));
            serviceBinder.AddMethod(__Method_GetTopPlayers, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Leaderboard.GetTopPlayersRequest, global::Leaderboard.GetTopPlayersResponse>(serviceImpl.GetTopPlayers));
        }

    }
}
#endregion
