// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: proto/wallet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserKey       string                 `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_proto_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *GetWalletRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *GetWalletRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_proto_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *GetWalletResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetWalletResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetWalletResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PurchaseItemARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserKey       string                 `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ReqId         string                 `protobuf:"bytes,3,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"` // 幂等键：客户端重发同 req_id 只扣一次
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseItemARequest) Reset() {
	*x = PurchaseItemARequest{}
	mi := &file_proto_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseItemARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseItemARequest) ProtoMessage() {}

func (x *PurchaseItemARequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseItemARequest.ProtoReflect.Descriptor instead.
func (*PurchaseItemARequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *PurchaseItemARequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *PurchaseItemARequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *PurchaseItemARequest) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

type PurchaseItemAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Cost          int64                  `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	Duplicate     bool                   `protobuf:"varint,5,opt,name=duplicate,proto3" json:"duplicate,omitempty"` // true 表示命中幂等，返回首次结果
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseItemAResponse) Reset() {
	*x = PurchaseItemAResponse{}
	mi := &file_proto_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseItemAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseItemAResponse) ProtoMessage() {}

func (x *PurchaseItemAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseItemAResponse.ProtoReflect.Descriptor instead.
func (*PurchaseItemAResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *PurchaseItemAResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PurchaseItemAResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *PurchaseItemAResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *PurchaseItemAResponse) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *PurchaseItemAResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *PurchaseItemAResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GrantKillRewardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserKey       string                 `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ReqId         string                 `protobuf:"bytes,3,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`                 // 幂等键
	KillId        string                 `protobuf:"bytes,4,opt,name=kill_id,json=killId,proto3" json:"kill_id,omitempty"`              // 击杀事件ID（业务标识）
	MonsterId     string                 `protobuf:"bytes,5,opt,name=monster_id,json=monsterId,proto3" json:"monster_id,omitempty"`     // 击杀怪物ID
	ScoreDelta    int32                  `protobuf:"varint,6,opt,name=score_delta,json=scoreDelta,proto3" json:"score_delta,omitempty"` // 奖励积分
	GoldReward    int64                  `protobuf:"varint,7,opt,name=gold_reward,json=goldReward,proto3" json:"gold_reward,omitempty"` // 奖励金币
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantKillRewardRequest) Reset() {
	*x = GrantKillRewardRequest{}
	mi := &file_proto_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantKillRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantKillRewardRequest) ProtoMessage() {}

func (x *GrantKillRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantKillRewardRequest.ProtoReflect.Descriptor instead.
func (*GrantKillRewardRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *GrantKillRewardRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *GrantKillRewardRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GrantKillRewardRequest) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *GrantKillRewardRequest) GetKillId() string {
	if x != nil {
		return x.KillId
	}
	return ""
}

func (x *GrantKillRewardRequest) GetMonsterId() string {
	if x != nil {
		return x.MonsterId
	}
	return ""
}

func (x *GrantKillRewardRequest) GetScoreDelta() int32 {
	if x != nil {
		return x.ScoreDelta
	}
	return 0
}

func (x *GrantKillRewardRequest) GetGoldReward() int64 {
	if x != nil {
		return x.GoldReward
	}
	return 0
}

type GrantKillRewardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Duplicate     bool                   `protobuf:"varint,3,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantKillRewardResponse) Reset() {
	*x = GrantKillRewardResponse{}
	mi := &file_proto_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantKillRewardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantKillRewardResponse) ProtoMessage() {}

func (x *GrantKillRewardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantKillRewardResponse.ProtoReflect.Descriptor instead.
func (*GrantKillRewardResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *GrantKillRewardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GrantKillRewardResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GrantKillRewardResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *GrantKillRewardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_wallet_proto protoreflect.FileDescriptor

const file_proto_wallet_proto_rawDesc = "" +
	"\n" +
	"\x12proto/wallet.proto\x12\x06wallet\"J\n" +
	"\x10GetWalletRequest\x12\x19\n" +
	"\buser_key\x18\x01 \x01(\tR\auserKey\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"a\n" +
	"\x11GetWalletResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"e\n" +
	"\x14PurchaseItemARequest\x12\x19\n" +
	"\buser_key\x18\x01 \x01(\tR\auserKey\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x15\n" +
	"\x06req_id\x18\x03 \x01(\tR\x05reqId\"\xb0\x01\n" +
	"\x15PurchaseItemAResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x03R\x04cost\x12\x1c\n" +
	"\tduplicate\x18\x05 \x01(\bR\tduplicate\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\xe1\x01\n" +
	"\x16GrantKillRewardRequest\x12\x19\n" +
	"\buser_key\x18\x01 \x01(\tR\auserKey\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x15\n" +
	"\x06req_id\x18\x03 \x01(\tR\x05reqId\x12\x17\n" +
	"\akill_id\x18\x04 \x01(\tR\x06killId\x12\x1d\n" +
	"\n" +
	"monster_id\x18\x05 \x01(\tR\tmonsterId\x12\x1f\n" +
	"\vscore_delta\x18\x06 \x01(\x05R\n" +
	"scoreDelta\x12\x1f\n" +
	"\vgold_reward\x18\a \x01(\x03R\n" +
	"goldReward\"\x85\x01\n" +
	"\x17GrantKillRewardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x12\x1c\n" +
	"\tduplicate\x18\x03 \x01(\bR\tduplicate\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\xf3\x01\n" +
	"\rWalletService\x12@\n" +
	"\tGetWallet\x12\x18.wallet.GetWalletRequest\x1a\x19.wallet.GetWalletResponse\x12L\n" +
	"\rPurchaseItemA\x12\x1c.wallet.PurchaseItemARequest\x1a\x1d.wallet.PurchaseItemAResponse\x12R\n" +
	"\x0fGrantKillReward\x12\x1e.wallet.GrantKillRewardRequest\x1a\x1f.wallet.GrantKillRewardResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_wallet_proto_rawDescOnce sync.Once
	file_proto_wallet_proto_rawDescData []byte
)

func file_proto_wallet_proto_rawDescGZIP() []byte {
	file_proto_wallet_proto_rawDescOnce.Do(func() {
		file_proto_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wallet_proto_rawDesc), len(file_proto_wallet_proto_rawDesc)))
	})
	return file_proto_wallet_proto_rawDescData
}

var file_proto_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_wallet_proto_goTypes = []any{
	(*GetWalletRequest)(nil),        // 0: wallet.GetWalletRequest
	(*GetWalletResponse)(nil),       // 1: wallet.GetWalletResponse
	(*PurchaseItemARequest)(nil),    // 2: wallet.PurchaseItemARequest
	(*PurchaseItemAResponse)(nil),   // 3: wallet.PurchaseItemAResponse
	(*GrantKillRewardRequest)(nil),  // 4: wallet.GrantKillRewardRequest
	(*GrantKillRewardResponse)(nil), // 5: wallet.GrantKillRewardResponse
}
var file_proto_wallet_proto_depIdxs = []int32{
	0, // 0: wallet.WalletService.GetWallet:input_type -> wallet.GetWalletRequest
	2, // 1: wallet.WalletService.PurchaseItemA:input_type -> wallet.PurchaseItemARequest
	4, // 2: wallet.WalletService.GrantKillReward:input_type -> wallet.GrantKillRewardRequest
	1, // 3: wallet.WalletService.GetWallet:output_type -> wallet.GetWalletResponse
	3, // 4: wallet.WalletService.PurchaseItemA:output_type -> wallet.PurchaseItemAResponse
	5, // 5: wallet.WalletService.GrantKillReward:output_type -> wallet.GrantKillRewardResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_wallet_proto_init() }
func file_proto_wallet_proto_init() {
	if File_proto_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wallet_proto_rawDesc), len(file_proto_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wallet_proto_goTypes,
		DependencyIndexes: file_proto_wallet_proto_depIdxs,
		MessageInfos:      file_proto_wallet_proto_msgTypes,
	}.Build()
	File_proto_wallet_proto = out.File
	file_proto_wallet_proto_goTypes = nil
	file_proto_wallet_proto_depIdxs = nil
}
