// 指定 proto3 语法

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: proto/leaderboard.proto

// 包名，防止命名冲突

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 提交分数的请求
type SubmitScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"` // 玩家名 (也可以用之前的 DbKey)
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`                            // 本次获得的分数 (注意：这里应该是总分，或者服务端逻辑去累加)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitScoreRequest) Reset() {
	*x = SubmitScoreRequest{}
	mi := &file_proto_leaderboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitScoreRequest) ProtoMessage() {}

func (x *SubmitScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitScoreRequest.ProtoReflect.Descriptor instead.
func (*SubmitScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitScoreRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *SubmitScoreRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 提交分数的响应 (可以为空，表示成功即可)
type SubmitScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitScoreResponse) Reset() {
	*x = SubmitScoreResponse{}
	mi := &file_proto_leaderboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitScoreResponse) ProtoMessage() {}

func (x *SubmitScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitScoreResponse.ProtoReflect.Descriptor instead.
func (*SubmitScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitScoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取排行榜的请求
type GetTopPlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // 希望获取前几名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopPlayersRequest) Reset() {
	*x = GetTopPlayersRequest{}
	mi := &file_proto_leaderboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPlayersRequest) ProtoMessage() {}

func (x *GetTopPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPlayersRequest.ProtoReflect.Descriptor instead.
func (*GetTopPlayersRequest) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopPlayersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 单个玩家的排名信息
type PlayerRankInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`                              // 排名
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"` // 玩家名
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`                            // 分数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRankInfo) Reset() {
	*x = PlayerRankInfo{}
	mi := &file_proto_leaderboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRankInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRankInfo) ProtoMessage() {}

func (x *PlayerRankInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRankInfo.ProtoReflect.Descriptor instead.
func (*PlayerRankInfo) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerRankInfo) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *PlayerRankInfo) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerRankInfo) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 获取排行榜的响应
type GetTopPlayersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 返回一个玩家排名信息的列表
	Players       []*PlayerRankInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopPlayersResponse) Reset() {
	*x = GetTopPlayersResponse{}
	mi := &file_proto_leaderboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPlayersResponse) ProtoMessage() {}

func (x *GetTopPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPlayersResponse.ProtoReflect.Descriptor instead.
func (*GetTopPlayersResponse) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_proto_rawDescGZIP(), []int{4}
}

func (x *GetTopPlayersResponse) GetPlayers() []*PlayerRankInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_proto_leaderboard_proto protoreflect.FileDescriptor

const file_proto_leaderboard_proto_rawDesc = "" +
	"\n" +
	"\x17proto/leaderboard.proto\x12\vleaderboard\"K\n" +
	"\x12SubmitScoreRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"/\n" +
	"\x13SubmitScoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x14GetTopPlayersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"[\n" +
	"\x0ePlayerRankInfo\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"N\n" +
	"\x15GetTopPlayersResponse\x125\n" +
	"\aplayers\x18\x01 \x03(\v2\x1b.leaderboard.PlayerRankInfoR\aplayers2\xbe\x01\n" +
	"\x12LeaderboardService\x12P\n" +
	"\vSubmitScore\x12\x1f.leaderboard.SubmitScoreRequest\x1a .leaderboard.SubmitScoreResponse\x12V\n" +
	"\rGetTopPlayers\x12!.leaderboard.GetTopPlayersRequest\x1a\".leaderboard.GetTopPlayersResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_leaderboard_proto_rawDescOnce sync.Once
	file_proto_leaderboard_proto_rawDescData []byte
)

func file_proto_leaderboard_proto_rawDescGZIP() []byte {
	file_proto_leaderboard_proto_rawDescOnce.Do(func() {
		file_proto_leaderboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_leaderboard_proto_rawDesc), len(file_proto_leaderboard_proto_rawDesc)))
	})
	return file_proto_leaderboard_proto_rawDescData
}

var file_proto_leaderboard_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_leaderboard_proto_goTypes = []any{
	(*SubmitScoreRequest)(nil),    // 0: leaderboard.SubmitScoreRequest
	(*SubmitScoreResponse)(nil),   // 1: leaderboard.SubmitScoreResponse
	(*GetTopPlayersRequest)(nil),  // 2: leaderboard.GetTopPlayersRequest
	(*PlayerRankInfo)(nil),        // 3: leaderboard.PlayerRankInfo
	(*GetTopPlayersResponse)(nil), // 4: leaderboard.GetTopPlayersResponse
}
var file_proto_leaderboard_proto_depIdxs = []int32{
	3, // 0: leaderboard.GetTopPlayersResponse.players:type_name -> leaderboard.PlayerRankInfo
	0, // 1: leaderboard.LeaderboardService.SubmitScore:input_type -> leaderboard.SubmitScoreRequest
	2, // 2: leaderboard.LeaderboardService.GetTopPlayers:input_type -> leaderboard.GetTopPlayersRequest
	1, // 3: leaderboard.LeaderboardService.SubmitScore:output_type -> leaderboard.SubmitScoreResponse
	4, // 4: leaderboard.LeaderboardService.GetTopPlayers:output_type -> leaderboard.GetTopPlayersResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_leaderboard_proto_init() }
func file_proto_leaderboard_proto_init() {
	if File_proto_leaderboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_leaderboard_proto_rawDesc), len(file_proto_leaderboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_leaderboard_proto_goTypes,
		DependencyIndexes: file_proto_leaderboard_proto_depIdxs,
		MessageInfos:      file_proto_leaderboard_proto_msgTypes,
	}.Build()
	File_proto_leaderboard_proto = out.File
	file_proto_leaderboard_proto_goTypes = nil
	file_proto_leaderboard_proto_depIdxs = nil
}
